FROM node:18.17-alpine AS base

# Create app directory
WORKDIR /app

# Install dependencies and build
FROM base AS builder
COPY package*.json ./
# Use clean-install with explicit cache clear to avoid cache locking issues
RUN npm cache clean --force && npm ci --no-cache
COPY . .
RUN npm run build

# Create production image
FROM base AS runner
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev --no-cache

# Expose port
EXPOSE 5000

# Start command
CMD ["node", "dist/index.js"] 