FROM node:18.17-alpine AS base

# Create app directory
WORKDIR /app

# Install dependencies and build
FROM base AS builder
COPY package*.json ./
RUN npm install --no-fund
COPY . .
RUN npm run build

# Create production image
FROM base AS runner
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev --no-fund

# Expose port
EXPOSE 5000

# Start command
CMD ["node", "dist/index.js"] 