[build]
builder = "NIXPACKS"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 